name: Debian nspawn Test

on:
  workflow_dispatch:

jobs:
  debian-x86:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y systemd-container debootstrap

      - name: Create Debian rootfs
        run: |
          sudo mkdir -p /var/lib/machines/debian

          sudo debootstrap stable /var/lib/machines/debian http://deb.debian.org/debian

      - name: Run Debian nspawn and echo running
        run: |
          sudo systemd-nspawn \
            -D /var/lib/machines/debian \
            --boot \
            --machine=debian \
            --quiet \
            /bin/bash -c 'echo running'