name: Mac Test

on:
  workflow_dispatch:

jobs:
  test-mac:
    # 必须明确指定 intel 镜像，macos-latest 现在是 ARM 芯片
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and Start Docker (via Colima)
        run: |
          brew install qemu colima docker
          colima start --network-address

      - name: Verify Docker
        run: |
          docker version
          docker run hello-world

      - name: Run your Mac tests
        run: |
          echo "在这里执行你的 Mac 测试脚本，同时可以调用上面的 Docker 容器"